# Lover's Concerto

How gentle is the rain

That falls softly on the meadow?

Birds, high up in the trees

Serenade the clouds with their melodies, oh, oh

See, there beyond the hill

The bright colors of the rainbow

Some magic from above

Made this day for us just to fall in love

Now, I belong to you

From this day until forever

Just love me tenderly

And I'll give to you every part of me

Oh oh, don't ever make me cry

Through long, lonely nights without us (uh uh uh)

Be always true to me

Keep this day in your heart eternally

Someday we shall return

To this place upon the meadow

We'll walk out in the rain

Hear the birds above singing once again, oh oh

You'll hold me in your arms

And say once again you love me

And if your love is true

Everything will be just as wonderful

You'll hold me in your arms

And say once again you love me

And if your love is true

Everything will be just as wonderful

You'll hold me in your arms

And say once again you love me

And if your love is true

Everything will be just as wonderful


# Sing

Sing, sing a song

Sing out loud

Sing out strong

Sing of good things not bad

Sing of happy not sad

Sing, sing a song

Make it simple to last

Your whole life long

Don't worry that it's not

Good enough for anyone

Else to hear

Just sing, sing a song

Sing, sing a song

Let the world sing along

Sing of love there could be

Sing for you and for me

Sing, sing a song

Make it simple to last

Your whole life long

Don't worry that it's not

Good enough for anyone

Else to hear

Just sing, sing a song

(Just sing, sing a song)

Just sing, sing a song



# Thousand years

Heart beats fast

Colors and promises

How to be brave?

How can I love when I'm afraid to fall?

But watching you stand alone

All of my doubt suddenly goes away somehow

One step closer

I have died every day waiting for you

Darling, don't be afraid

I have loved you for a thousand years

I'll love you for a thousand more

Time stands still

Beauty in all she is

I will be brave

I will not let anything take away

What's standing in front of me

Every breath, every hour has come to this

One step closer

I have died every day waiting for you

Darling, don't be afraid

I have loved you for a thousand years

I'll love you for a thousand more

And all along I believed I would find you

Time has brought your heart to me

I have loved you for a thousand years

I'll love you for a thousand more

One step closer

One step closer

I have died every day waiting for you

Darling, don't be afraid

I have loved you for a thousand years

I'll love you for a thousand more

And all along I believed I would find you

Time has brought your heart to me

I have loved you for a thousand years

I'll love you for a thousand more


# Always remember us this way

That Arizona sky burnin' in your eyes

You look at me and, babe, I wanna catch on fire

It's buried in my soul like California gold

You found the light in me that I couldn't find

So when I'm all choked up

And I can't find the words

Every time we say goodbye

Baby, it hurts

When the sun goes down

And the band won't play

I'll always remember us this way

Lovers in the night

Poets tryin' to write

We don't know how to rhyme

But, damn, we try

But all I really know

You're where I wanna go

The part of me that's you will never die

So when I'm all choked up

And I can't find the words

Every time we say goodbye

Baby, it hurts

When the sun goes down

And the band won't play

I'll always remember us this way

Oh, yeah

I don't wanna be just a memory, baby, yeah

Hoo, hoo, hoo, hoo

Hoo, hoo, hoo, hoo

Hoo, hoo, hoo, hoo, hoo

So when I'm all choked up

And I can't find the words

Every time we say goodbye

Baby, it hurts

When the sun goes down

And the band won't play

I'll always remember us this way, way, yeah

When you look at me

And the whole world fades

I'll always remember us this way


# A time for us

A time for us some day there'll be

When chains are torn by courage born of a love that's free

A time when dreams so long denied

Can flourish as we unveil the love we now must hide



A time for us at last to see

A life worthwhile for you and me



And with our love through tears and thorns

We will endure as we pass surely through every storm

A time for us some day there'll be a new world

A world of shining hope for you and me


For you and me

And with our love through tears and thorns

We will endure as we pass surely through every storm

A time for us some day there'll be a new world

A world of shining hope for you and me


A world of shining hope for you and me



# You Raise Me Up

[Verse]

When I am down, and, oh, my soul so weary

When troubles come and my heart burdened be

Then I am still and wait here in the silence

Until You come and sit awhile with me

[Chorus]

You raise me up so I can stand on mountains

You raise me up to walk on stormy seas

I am strong when I am on your shoulders

You raise me up to more than I can be

[Instrumental Break]

[Chorus]
You raise me up so I can stand on mountains

You raise me up to walk on stormy seas

I am strong when I am on your shoulders

You raise me up to more than I can be

You raise me up (Up) so I can stand on mountains (Stand on mountains)

You raise me up to walk on stormy seas (Stormy seas)

I am strong (I am strong) when I am on your shoulders (Ooh-ooh)

You raise me up to more than I can be

You raise me up (Up) so I can stand on mountains (Stand on mountains)

You raise me up to walk on stormy seas (Stormy seas)

I am strong when I am on your shoulders

You raise me up to more than I can be

[Outro]

You raise me up to more than I can be

# She

[Verse 1]

She may be the face I can't forget

A trace of pleasure or regret

May be my treasure or the price I have to pay

She may be the song that summer sings

May be the chill that autumn brings

May be a hundred different things

Within the measure of a day


[Verse 2]

She may be the beauty or the beast

May be the famine or the feast

May turn each day into a heaven or a hell

She may be the mirror of my dreams

A smile reflected in a stream

She may not be what she may seem

Inside her shell


[Verse 3]

She, who always seems so happy in a crowd

Whose eyes can be so private and so proud

No one's allowed to see them when they cry

She may be the love that cannot hope to last

May come to me from shadows of the past

That I'll remember till the day I die


[Verse 4]

She may be the reason I survive

The why and wherefore I'm alive

The one I'll care for through the rough and ready years

Me, I'll take her laughter and her tears

And make them all my souvenirs

For where she goes, I've got to be

The meaning of my life is she


She

Oh, she


# If

[Verse 1]

If a picture paints a thousand words

Then why can't I paint you?

The words will never show

The you I've come to know


[Verse 2]

If a face could launch a thousand ships

Then where am I to go?

There's no one home but you

You're all that's left me too

[Chorus]

And when my love for life is running dry

You come and pour yourself on me

[Verse 3]

If a man could be two places at one time

I'd be with you

Tomorrow and today

Beside you all the way

[Verse 4]

If the world should stop revolving

Spinning slowly down to die

I'd spend the end with you

And when the world was through


[Chorus]

Then one by one the stars would all go out

Then you and I would simply fly away


# White Christmas

I'm dreaming of a white Christmas

Just like the ones I used to know (Ooh)

Where the treetops glisten and children listen

To hear sleigh bells in the snow


I'm dreaming of a white Christmas

With every Christmas card I write (Ooh)

May your days be merry and bright

And may all your Christmases be white



I'm dreaming of a white Christmas

Just like the ones I used to know (Ooh)

Where the treetops glisten and children listen

To hear (To hear the sleigh bеlls in the snow)


I'm dreaming of a white Christmas

With еvery Christmas card I write (Mm)

May your days be merry and bright

And may all your Christmases be white (Mm)
Mm-mm-mm (Mm)


# Shape of my heart

He deals the cards as a meditation

And those he plays never suspect

He doesn't play for the money he wins

He don't play for respect

He deals the cards to find the answer

The sacred geometry of chance

The hidden law of a probable outcome

The numbers lead a dance

I know that the spades are the swords of a soldier

I know that the clubs are weapons of war

I know that diamonds mean money for this art

But that's not the shape of my heart

He may play the jack of diamonds

He may lay the queen of spades

He may conceal a king in his hand

While the memory of it fades

I know that the spades are the swords of a soldier

I know that the clubs are weapons of war

I know that diamonds mean money for this art

But that's not the shape of my heart

That's not the shape

The shape of my heart

If I told her that I loved you

You'd maybe think there's something wrong

I'm not a man of too many faces

The mask I wear is one

But those who speak know nothing

And find out to their cost

Like those who curse their luck in too many places

And those who fear are lost

I know that the spades are the swords of a soldier

I know that the clubs are weapons of war

I know that diamonds mean money for this art

But that's not the shape of my heart

That's not the shape of my heart

That's not the shape

The shape of my heart


# All I Want For Christmas Is You

[Intro]

I don't want a lot for Christmas

There is just one thing I need

I don't care about the presents

Underneath the Christmas tree

I just want you for my own

More than you could ever know

Make my wish come true

All I want for Christmas is you, yeah


[Verse 1]

I don't want a lot for Christmas

There is just one thing I need (And I)

Don't care about the presents

Underneath the Christmas tree

I don't need to hang my stocking

There upon the fireplace (Ah)

Santa Claus won't make me happy

With a toy on Christmas Day


[Chorus]

I just want you for my own (Ooh)

More than you could ever know (Ooh)

Make my wish come true

All I want for Christmas is you

You, baby

[Verse 2]

Oh, I won't ask for much this Christmas

I won't even wish for snow (And I)

I'm just gonna keep on waiting

Underneath the mistletoe

I won't make a list and send it

To the North Pole for Saint Nick (Ah)

I won't even stay awake to

Hear those magic reindeer click

[Chorus]

'Cause I just want you here tonight (Ooh)

Holding on to me so tight (Ooh)

What more can I do?

Oh baby, all I want for Christmas is you

You, baby



[Bridge]
Oh, all the lights are shining

So brightly everywhere (So brightly, baby)

And the sound of children's

Laughter fills the air (Oh, oh yeah)

And everyone is singing (Oh yeah)

I hear those sleigh bells ringing (Oh)

Santa, won't you bring me the one I really need? (Yeah, oh, oh)

Won't you please bring my baby to me?


# Don’t Forget to Remember

Oh my heart won't believe that you have left me

I keep telling my self that it's true

I can get over anything you want my love

But I can't get myself over you

Don't forget to remember me

And the love that used to be I still remember youI love you

In my heart lies a memory to tell the stars above

Don't forget to remember me my love

On my wall lies a photograph of you girl

Though I try to forget you somehow

You're the mirror of my soul so take me out of my hole

Let me try to go on living right now

Don't forget to remember me

And the love that used to be

I still remember you

I love you

In my heart lies a memory to tell the stars above

Don't forget to remember me my love


# Right Here Waiting

Oceans apart, day after day

And I slowly go insane

I hear your voice on the line

But it doesn't stop the pain

If I see you next to never

Then how can we say forever?

Wherever you go

Whatever you do

I will be right here waiting for you

Whatever it takes

Or how my heart breaks

I will be right here waiting for you

I took for granted, all the times

That I thought would last somehow

I hear the laughter, I taste the tears

But I can't get near you now

Oh, can't you see it, baby?

You've got me going crazy

Wherever you go

Whatever you do

I will be right here waiting for you

Whatever it takes

Or how my heart breaks

I will be right here waiting for you

I wonder how we can survive

This romance

But in the end if I'm with you

I'll take the chance

Oh, can't you see it, baby?

You've got me going crazy

Wherever you go

Whatever you do

I will be right here waiting for you

Whatever it takes

Or how my heart breaks

I will be right here waiting for you

Waiting for you

# Sorry you are only lonely

[Verse 1]

When the world is ready to fall

On your little shoulders

And when you're feeling lonely and small

You need somebody there to hold you

[Chorus]

You can call out my name

When you're only lonely

Now don't you ever be ashamed

You're only lonely

[Verse 2]

When you need somebody around

On the nights that try you

Remember, I was there when you were a queen

And I'll be the last one there beside you

[Chorus]

So you can call out my name

When you're only lonely

Now don't you ever be ashamed

You're only lonely

[Post-Chorus]

(You're only lonely)

(You're only lonely)

(You're only lonely)

(Ooh)

# Like I am gonna lose you

I found myself dreaming in silver and gold

Like a scene from a movie that every broken heart knows

We were walking on moonlight, and you pulled me close

Split second and you disappeared and then I was all alone

I woke up in tears with you by my side

A breath of relief, and I realized

No, we're not promised tomorrow

So I'm gonna love you like I'm gonna lose you

I'm gonna hold you like I'm saying goodbye

Wherever we're standing, I won't take you for granted

'Cause we'll never know when, when we'll run out of time

So I'm gonna love you like I'm gonna lose you (lose you)

I'm gonna love you like I'm gonna lose you

In the blink of an eye, just a whisper of smoke

You could lose everything, the truth is you never know

So I'll kiss you longer, baby (hey), any chance that I get

I'll make the most of the minutes and love with no regret

Let's take our time to say what we want (say what we want)

Use what we got before it's all gone (all gone)

'Cause no (no), we're not promised tomorrow

So I'm gonna love you like I'm gonna lose you (lose you)

I'm gonna hold you (hey) like I'm saying goodbye

Wherever we're standing (yeah), I won't take you for granted

'Cause we'll never know when, when we'll run out of time

So I'm gonna love you (I'm gonna love you)

Like I'm gonna lose you (like I'm gonna lose you)

I'm gonna love you (love) like I'm gonna lose you

I'm gonna love you (oh)

Like I'm gonna lose you (like I'm gonna lose you)

I'm gonna hold you like I'm saying goodbye

Wherever we're standing, I won't take you for granted

'Cause we'll never know when, when we'll run out of time

So I'm gonna love you (I'm gonna love you, baby)

Like I'm gonna lose you (like I'm gonna lose you)

I'm gonna love you (oh) like I'm gonna lose you


# Nothing without Love

I am nothing without love

I'm but a ship stuck in the sand

Some would say that I'm all alone

But I am, I'm nothing without love

I wanna hold her in my arms

But she feeling low, she feeling sad

I would take credit for what's wrong

But I am, I'm nothing without love

Three years at sea after the storm

In this sinking ship that love had put me on

God, I wish a gust of wind would come and carry me home

But I, I got nowhere to go

Now here you show up with the force of a wave

And so I'm setting my sail, I'm headed for the empire state, hey-hey

I don't wanna lose this one, she made me feel whole

You know I am, I'm nothing without love

Oh, baby, show me a sign

Send up a signal that everything's fine

Come on slide up right here by my side

You know that I, I wanna rest in your life

Na-na-na, hey, na-na-na, oh

Na-na-na, hey, na-na-na, oh

Na-na-na, hey, na-na-na, oh

Na-na-na, hey, na-na-na, oh (I wanna rest in your life)

Na-na-na, hey, na-na-na, oh

Na-na-na, hey, na-na-na, oh

Na-na-na, hey, na-na-na, oh

Na-na-na, hey

I am nothing without love

I'm just these thoughts without a pen

And I would take credit for this song

But I am nothing without love

Baby, show me a sign

Send up a signal that everything's fine

Oh, just come on, come one, come on, come on right by my side

Don't you know that I, don't you know that I, I wanna rest in your life

I wanna rest in your life

I wanna rest in your life

'Cause I am, I'm nothing without love

# Perhpas Love

Perhaps love is like a resting place

A shelter from the storm

It exists to give you comfort

It is there to keep you warm

And in those times of trouble

When you are most alone

The memory of love will bring you home

Perhaps love is like a window

Perhaps an open door

It invites you to come closer

It wants to show you more

And even if you lose yourself

And don't know what to do

The memory of love will see you through

Oh, love to some is like a cloud

To some as strong as steel

For some a way of living

For some a way to feel

And some say love is holding on

And some say letting go

And some say love is everything

And some say they don't know

Perhaps love is like the ocean

Full of conflict, full of change

Like a fire when it's cold outside

Or thunder when it rains

If I should live forever

And all my dreams come true

My memories of love will be of you

# Sailing

[Verse 1]

Well, it's not far down to paradise

At least it's not for me

And if the wind is right, you can sail away

And find tranquility

Oh, the canvas can do miracles

Just you wait and see

Believe me

[Verse 2]

It's not far to never never land

No reason to pretend

And if the wind is right, you can find the joy

Of innocence again

Oh, the canvas can do miracles

Just you wait and see

Believe me

[Chorus]

Sailing

Takes me away to where I've always heard it could be

Just a dream and the wind to carry me

Soon, I will be free

[Verse 3]

Fantasy

It gets the best of me

When I'm sailing

All caught up in the reverie

Every word is a symphony

Won't you believe me?


# Someone Like You

I heard that you're settled down

That you found a girl and you're married now

I heard that your dreams came true

Guess she gave you things, I didn't give to you

Old friend, why are you so shy?

Ain't like you to hold back or hide from the light

I hate to turn up out of the blue, uninvited

But I couldn't stay away, I couldn't fight it

I had hoped you'd see my face

And that you'd be reminded that for me, it isn't over

Never mind, I'll find someone like you

I wish nothing but the best for you, too

"Don't forget me, " I beg

I remember you said

"Sometimes it lasts in love, but sometimes it hurts instead"

"Sometimes it lasts in love, but sometimes it hurts instead"

You know how the time flies

Only yesterday was the time of our lives

We were born and raised in a summer haze

Bound by the surprise of our glory days

I hate to turn up out of the blue, uninvited

But I couldn't stay away, I couldn't fight it

I had hoped you'd see my face

And that you'd be reminded that for me, it isn't over

Never mind, I'll find someone like you

I wish nothing but the best for you, too

"Don't forget me, " I begged

I remember you said

"Sometimes it lasts in love, but sometimes it hurts instead"

Nothing compares, no worries or cares

Regrets and mistakes, they're memories made

Who would have known how bittersweet this would taste?

Never mind, I'll find someone like you

I wish nothing but the best for you

"Don't forget me, " I beg

I remember you said

"Sometimes it lasts in love, but sometimes it hurts instead"

Never mind, I'll find someone like you

I wish nothing but the best for you, too

"Don't forget me, " I begged

I remember you said

"Sometimes it lasts in love, but sometimes it hurts instead"

"Sometimes it lasts in love, but sometimes it hurts instead"

# Seven Daffoldils

I may not have a mansion

I haven't any land

Not even a paper dollar

To crinkle in my hands

But I can show you morning on a thousand hills

And kiss you and give you seven daffodils

I do not have a fortune

To buy you pretty things

But I can weave you moonbeams

For necklaces and rings

And I can show you morning on a thousand hills

And kiss you and give you seven daffodils

On seven golden daffodils

All shining in the sun

To light our way to evening

When our day is done

And I will give you music and a crust of bread

A pillow of piny boughs to rest your head

A pillow of piny boughs to rest your 

# See You Again

[Intro: Tyler, The Creator]

Okay, okay, okay, okay, okay, okay, o—

[Verse 1: Tyler, The Creator]

You live in my dream state

Relocate my fantasy

I stay in reality

You live in my dream state

Any time I count sheep

That's the only time we make up, make up

You exist behind my eyelids, my eyelids

Now, I don't wanna wake up



[Pre-Chorus: Tyler, The Creator, Tyler, The Creator & Kali Uchis]

20/20, 20/20 visions

Cupid hit me, Cupid hit me with precision, I

Wonder if you look both ways when you cross my mind (Yeah)

I said, I said

I'm sick of, sick of, sick of, sick of chasing

You're the one that's always running through my daydream, I

I can only see your face when I close my eyes

(Uh-huh)



[Chorus: Kali Uchis & Tyler, The Creator]

Can I get a kiss? (Ah)

And can you make it last forever? (I said)

I said I'm 'bout to go to war (Uh-huh)

And I don't know if I'ma see you again

Can I get a kiss? (Can I?)

And can you make it last forever? (Can you?)

I said I'm 'bout to go to war ('Bout to)

And I don't know if I'ma see you again

Ayy, switch it up

# Feelings

[Verse 1]

Feelings, nothing more than feelings

Trying to forget my feelings of love

Teardrops rolling down on my face

Trying to forget my feelings of love


[Chorus]

Feelings, for all my life I'll feel it

I wish I've never met you, girl

You'll never come again

Feelings, whoa, oh, oh, feelings

Whoa, oh, oh, feel it again in my arms


[Verse 2]

Feelings, feelings like I've never lost you

And feelings like I've never have you again in my heart

[Chorus]

Feelings, for all my life I'll feel it

I wish I've never met you, girl

You'll never come again

[Verse 2]

Feelings, feelings like I've never lost you

And feelings like I've never have you again in my life

# Always Remember Us This Way

That Arizona sky burnin' in your eyes

You look at me and, babe, I wanna catch on fire

It's buried in my soul like California gold

You found the light in me that I couldn't find

So when I'm all choked up

And I can't find the words

Every time we say goodbye

Baby, it hurts

When the sun goes down

And the band won't play

I'll always remember us this way

Lovers in the night

Poets tryin' to write

We don't know how to rhyme

But, damn, we try

But all I really know

You're where I wanna go

The part of me that's you will never die

So when I'm all choked up

And I can't find the words

Every time we say goodbye

Baby, it hurts

When the sun goes down

And the band won't play

I'll always remember us this way

Oh, yeah

I don't wanna be just a memory, baby, yeah

Hoo, hoo, hoo, hoo

Hoo, hoo, hoo, hoo

Hoo, hoo, hoo, hoo, hoo

So when I'm all choked up

And I can't find the words

Every time we say goodbye

Baby, it hurts

When the sun goes down

And the band won't play

I'll always remember us this way, way, yeah

When you look at me

And the whole world fades

I'll always remember us this way


# Golden

I was a ghost, I was alone (hah)

어두워진 앞길 속에 (hah)

Given the throne, I didn't know how to believe

I was the queen that I'm meant to be

I lived two lives, tried to play both sides

But I couldn't find my own place

Called a problem child 'cause I got too wild

But now that's how I'm getting paid 끝없이 on stage

I'm done hidin', now I'm shinin' like I'm born to be

We dreamin' hard, we came so far, now I'll believe

We're goin' up, up, up, it's our moment

You know together we're glowing

Gonna be, gonna be golden

Oh, up, up, up with our voices

영원히 깨질 수 없는

Gonna be, gonna be golden

Oh, I'm done hidin', now I'm shinin' like I'm born to be

Oh, our time, no fears, no lies

That's who we're born to be

Waited so long to break these walls down

To wake up and feel like me

Put these patterns all in the past now

And finally live like the girl they all see

No more hiding, I'll be shining like I'm born to be

'Cause we are hunters, voices strong, and I know I'll believe

We're goin' up, up, up, it's our moment

You know together we're glowing

Gonna be, gonna be golden

Oh, up, up, up, with our voices

영원히 깨질 수 없는

Gonna be, gonna be golden

Oh, I'm done hidin', now I'm shining like I'm born to be

Oh, our time, no fears, no lies

That's who we're born to be

You know we're gonna be, gonna be golden

We're gonna be, gonna be

Born to be, born to be glowin'

밝게 빛나는 우린

You know that it's our time, no fears, no lies

That's who we're born to be


# Love Story

Where do I begin

To tell the story of how great a love can be

The sweet love story that is older than the sea

The simple truth about the love she brings to me

Where do I start

With her first hello

She gave new meaning to this empty world of mine

There'd never be another love, another time

She came into my life and made the living fine

She fills my heart

She fills my heart with very special things

With angels' songs, with wild imaginings

She fills my soul with so much love

That anywhere I go I'm never lonely

With her around, who could be lonely

I reach for her hand, it's always there

How long does it last

Can love be measured by the hours in a day

I have no answers now but this much I can say

I know I'll need her 'til the stars all burn away

And she'll be there

How long does it last

Can love be measured by the hours in a day

I have no answers now but this much I can say

I know I'll need her 'til the stars all burn away

And she'll be there


# Say You Say Me

Say you, say me

Say it for always

That's the way it should be

Say you, say me

Say it together, naturally

I had a dream, I had an awesome dream

People in the park playing games in the dark

And what they played was a masquerade

And from behind the walls of doubt

A voice was crying out

Say you, say me

Say it for always

That's the way it should be

Say you, say me

Say it together, naturally

As we go down life's lonesome highway

Seems the hardest thing to do is to find a friend or two

That helping hand

Someone who understands

That when you feel you've lost your way

You've got someone there to say, "I'll show you"

Say you, say me

Say it for always (oh)

That's the way it should be

Say you, say me

Say it together, naturally

So you think you know the answers? Oh no

Well the whole world's got you dancing

That's right, I'm telling you

Time to start believing, oh yes

Believe in who you are

You are a shining star

Say you, say me

Say it for always

Oh, that's the way it should be

Say you, say me

Say it together, naturally

Say it together, naturally

# All of Me
What would I do without your smart mouth?

Drawing me in, and you kicking me out

You've got my head spinning, no kidding, I can't pin you down

What's going on in that beautiful mind?

I'm on your magical mystery ride

And I'm so dizzy, don't know what hit me, but I'll be alright

My head's under water

But I'm breathing fine

You're crazy and I'm out of my mind

'Cause all of me

Loves all of you

Love your curves and all your edges

All your perfect imperfections

Give your all to me

I'll give my all to you

You're my end and my beginning

Even when I lose, I'm winning

'Cause I give you all of me

And you give me all of you, oh-oh

How many times do I have to tell you?

Even when you're crying, you're beautiful too

The world is beating you down, I'm around through every mood

You're my downfall, you're my muse

My worst distraction, my rhythm and blues

I can't stop singing, it's ringing in my head for you

My head's under water

But I'm breathing fine

You're crazy and I'm out of my mind

'Cause all of me

Loves all of you

Love your curves and all your edges

All your perfect imperfections

Give your all to me

I'll give my all to you

You're my end and my beginning

Even when I lose, I'm winning

'Cause I give you all of me

And you give me all of you, oh-oh

Give me all of you, oh

Cards on the table, we're both showing hearts

Risking it all, though it's hard

'Cause all of me

Loves all of you

Love your curves and all your edges

All your perfect imperfections

Give your all to me

I'll give my all to you

You're my end and my beginning

Even when I lose, I'm winning

'Cause I give you all of me

And you give me all of you

I give you all of me

And you give me all of you, oh-oh


# You Say


I keep fighting voices in my mind that say I'm not enough

Every single lie that tells me I will never measure up

Am I more than just the sum of every high and every low?

Remind me once again just who I am because I need to know

Ooh-oh

You say I am loved when I can't feel a thing

You say I am strong when I think I am weak

And you say I am held when I am falling short

And when I don't belong, oh, You say I am Yours

And I believe (I), oh, I believe (I)

What You say of me (I)

I believe

The only thing that matters now is everything You think of me

In You, I find my worth, in You, I find my identity

Ooh-oh

You say I am loved when I can't feel a thing

You say I am strong when I think I am weak

And you say I am held when I am falling short

When I don't belong, oh, You say I am Yours

And I believe (I), oh, I believe (I)

What You say of me (I)

Oh, I believe

Taking all I have, and now I'm laying it at Your feet

You have every failure, God, You have every victory

Ooh-oh

You say I am loved when I can't feel a thing

You say I am strong when I think I am weak

You say I am held when I am falling short

When I don't belong, oh, You say I am Yours

And I believe (I), oh, I believe (I)

What You say of me (I)

I believe

Oh, I believe (I)

Yes, I believe (I)

What You say of me (I)

I believe


# Flowers

We were good, we were gold

Kinda dream that can't be sold

We were right 'til we weren't

Built a home and watched it burn

Mm, I didn't wanna leave you, I didn't wanna lie

Started to cry, but then remembered I

I can buy myself flowers

Write my name in the sand

Talk to myself for hours

Say things you don't understand

I can take myself dancing

And I can hold my own hand

Yeah, I can love me better than you can

Can love me better, I can love me better, baby

Can love me better, I can love me better, baby

Paint my nails cherry red

Match the roses that you left

No remorse, no regret

I forgive every word you said

Ooh, I didn't wanna leave you, baby, I didn't wanna fight

Started to cry, but then remembered I

I can buy myself flowers

Write my name in the sand

Talk to myself for hours, yeah

Say things you don't understand

I can take myself dancing, yeah

I can hold my own hand

Yeah, I can love me better than you can

Can love me better, I can love me better, baby

Can love me better, I can love me better, baby

Can love me better, I can love me better, baby

Can love me better, I- (ooh, I)

I didn't wanna leave you, I didn't wanna fight

Started to cry, but then remembered I

I can buy myself flowers (uh-huh)

Write my name in the sand

Talk to myself for hours (yeah)

Say things you don't understand (you never will)

I can take myself dancing, yeah

I can hold my own hand

Yeah, I can love me better than

Yeah, I can love me better than you can

Can love me better, I can love me better, baby (oh, oh)

Can love me better, I can love me better, baby (than you can)

Can love me better, I can love me better, baby

Can love me better, I-

# How Deep Is Your Love


I know your eyes in the morning sun

I feel you touch me in the pouring rain

And the moment that you wander far from me

I wanna feel you in my arms again

And you come to me on a summer breeze

Keep me warm in your love, then you softly leave

And it's me you need to show

How deep is your love?

How deep is your love?

How deep is your love?

I really mean to learn

'Cause we're living in a world of fools

Breaking us down when they all should let us be

We belong to you and me

I believe in you

You know the door to my very soul

You're the light in my deepest, darkest hour

You're my savior when I fall

And you may not think I care for you

When you know down inside that I really do

And it's me you need to show

How deep is your love?

How deep is your love?

How deep is your love?

I really mean to learn

'Cause we're living in a world of fools

Breaking us down when they all should let us be

We belong to you and me

Na-na-na-na-na

Na-na-na-na-na-na-na-na

Na-na-na-na-na-na-na-na-na

Na-na-na-na-na-na-na

And you come to me on a summer breeze

Keep me warm in your love, then you softly leave

And it's me you need to show

How deep is your love?

How deep is your love?

How deep is your love?

I really mean to learn

'Cause we're living in a world of fools

Breaking us down when they all should let us be

We belong to you and me (na-na-na-na-na)

How deep is your love?

How deep is your love?

I really mean to learn

'Cause we're living in a world of fools

Breaking us down when they all should let us be

We belong to you and me (na-na-na-na-na)

How deep is your love?

How deep is your love?

I really mean to learn

'Cause we're living in a world of fools

Breaking us down when they all should let us be

We belong to you and me
