
# More than I can say

Oh oh, yea, yea

I love you more than I can say

I'll love you twice as much tomorrow

Oh love you more than I can say

Oh oh, yea, yea

I miss you every single day

Why must my life be filled with sorrow

Oh love you more than I can say

Don't you know I need you so

Tell me please I gotta know

Do you mean to make me cry

Am I just another guy

Oh oh, yea, yea

I miss you more than i can say

Why must my life be filled with sorrow

Oh love you more than I can say

Oh, don't you know I need you so

So tell me please I gotta know

Do you mean to make me cry

Am I just another guy

Oh oh, yea, yea

I love you more than I can say

I'll love you twice as much tomorrow

Oh love you more than I can say

I love you more than I can say

I love you more than I can say (more than I can say)

I love you twice as much tomorrow (more than I can say)

I love you twice as much tomorrow

I love you more than I can say

(More than I can say) I love you more than words can say yeah



# Someone You Loved

I'm going under, and this time, I fear there's no one to save me

This all or nothing really got a way of driving me crazy

I need somebody to hear, somebody to know

Somebody to have, somebody to hold

It's easy to say, but it's never the same

I guess I kinda liked the way you numbed all the pain



[Chorus]

Now, the day bleeds into nightfall

And you're not here to get me through it all

I let my guard down and then you pulled the rug

I was getting kinda used to being someone you loved



[Verse 2]

I'm going under, and this time, I fear there's no one to turn to

This all-or-nothing way of loving got me sleeping without you

Now, I need somebody to know, somebody to hear

Somebody to have, just to know how it feels

It's easy to say, but it's never the same

I guess I kinda like the way you help me escape



[Chorus]

Now, the day bleeds into nightfall

And you're not here to get me through it all

I let my guard down and then you pulled the rug

I was getting kinda used to being someone you loved



[Bridge]

And I tend to close my eyes when it hurts sometimes

I fall into your arms

I'll be safe in your sound till I come back around



[Chorus]

For now, the day bleeds into nightfall

And you're not here to get me through it all

I let my guard down and then you pulled the rug

I was getting kinda used to being someone you loved

But now the day bleeds into nightfall

And you're not here to get me through it all

I let my guard down and then you pulled the rug

I was getting kinda used to being someone you loved

I let my guard down and then you pulled the rug

I was getting kinda used to being someone you loved

# Endless Love

My love, there's only you in my life

The only thing that's right

My first love

You're every breath that I take

You're every step I make

And I, I want to share

All my love with you

No one else will do

And your eyes, your eyes, your eyes

They tell me how much you care

Ooh, yes

You will always be

My endless love

Two hearts

Two hearts that beat as one

Our lives have just begun

Forever (oh)

I'll hold you close in my arms

I can't resist your charms

And love, oh love

I'll be a fool for you I'm sure

You know I don't mind (oh)

You know I don't mind

'Cause you

You mean the world to me (oh)

I know, I know

I've found, I've found in you

My endless love

Ohh

Boom, boom

Boom, boom, boom boom, boom, boom

Boom, boom, boom boom, boom

Oh, and love oh, love

I'll be that fool for you I'm sure

You know I don't mind

Oh, you know I don't mind

And, yes

You'll be the only one

'Cause no one can deny

This love I have inside

And I'll give it all to you

My love, my love, my love

My endless love



# Rain

Listen to the pouring rain, listen to it pour

And with every drop of rain you know I love you more

Let it rain all night long

Let my love for you grow strong

As long as we're together

Who cares about the weather

Listen to the falling rain, listen to it fall

And with every drop of rain I can hear you call

Call my name right out loud

I can hear above the clouds

And down here among the puddles

You and I together huddle

Listen to the falling rain, listen to the rain

It's raining, it's pouring

The old man is snoring

Went to bed and he bumped his head

Wouldn't get up in the morning

Listen to the falling rain, listen to it fall

And with every drop of rain I can hear you call

Call my name right out loud

I can hear above the clouds

And down here among the puddles

You and I together huddle

Listen to the falling rain, listen to the rain

Listen to the pouring rain, listen to the rain

It keeps on falling, it keeps on falling

Listen to the rain on my window pane

Listen to the rain on my window pane

Listen to the rain, listen to the rain

Listen to the rain, listen to the rain



# Just When I needed You Most

[Verse 1]

You packed in the morning, I stared out the window

And I struggled for something to say

You left in the rain without closing the door

I didn't stand in your way



[Chorus]

But I miss you more than I missed you before

And now where I'll find comfort, God knows

'Cause you left me just when I needed you most

(Left me just when I needed you most)



[Verse 2]

Now most every morning, I stare out the window

And I think about where you might be

I've written you letters that I'd like to send

If you would just send one to me



[Chorus]

'Cause I need you more than I needed before

And now where I'll find comfort, God knows

'Cause you left me just when I needed you most

(Left me just when I needed you most)



[Verse 3]

You packed in the morning, I stared out the window

And I struggled for something to say

You left in the rain without closing the door

I didn't stand in your way


[Chorus]

Now I love you more than I loved you before

And now where I'll find comfort, God knows

'Cause you left me just when I needed you most

Oh yeah, you left me just when I needed you most

You left me just when I needed you most




# Sunrise Sunset

Is this the little girl I carried

Is this the little boy at play?

I don't remember growing older

When did they?

When did she get to be a beauty

When did he grow to be so tall?

Wasn't it yesterday that they were small?

Sunrise, sunset

Sunrise, sunset

Swiftly flow the days

Seedlings turn overnight to sunflowers

Blossoming even as they gaze

Sunrise, sunset

Sunrise, sunset

Swiftly fly the years

One season following another

Laden with happiness and tears

One season following another

Laden with happiness and tears (Sunrise, sunset)

(Sunrise, sunset)

 


# Heal the world

[Intro: Child]

Think about, um, the generations, and, uh, say we wanna make it a better place for our children and children's children so that they, they, they s— they know it's a better world for them. Think they can make it a better place



[Verse 1: Michael Jackson]

There's a place in your heart

And I know that it is love

And this place could much brighter than tomorrow

And if you really try

You'll find there's no need to cry

In this place, you'll feel there's no hurt or sorrow



[Pre-Chorus: Michael Jackson]

There are ways to get there

If you care enough for the living

Make a little space

Make a better place



[Chorus: Michael Jackson]

Heal the world

Make it a better place

For you and for me and the entire human race

There are people dying

If you care enough for the living

Make a better place for you and for me



[Verse 2: Michael Jackson]

If you want to know why

There's a love that cannot lie

Love is strong, it only cares for joyful giving

If we try, we shall see

In this bliss, we cannot feel

Fear or dread, we stop existing and start living
