# Golden

I was a ghost, I was alone (Hah)

어두워진 (Hah) 앞길속에 (Hah)

Given the throne, I didn't know how to believe (Hah)

I was the queen that I'm meant to be (Ah)

I lived two lives, tried to play both sides

But I couldn't find my own place (Oh, oh)

Called a problem child 'cause I got too wild

But now that's how I'm getting paid, 끝없이 on stage


I'm done hidin', now I'm shinin'

Like I'm born to be

We dreamin' hard, we came so far

Now I believe


We're goin' up, up, up

It's our moment

You know together we're glowin'

Gonna be, gonna be golden

Oh, up, up, up

With our voices

영원히 깨질 수 없는

Gonna be, gonna be golden


# Love Story

Where do I begin

To tell the story of how great a love can be

The sweet love story that is older than the sea

The simple truth about the love she brings to me

Where do I start

With her first hello

She gave new meaning to this empty world of mine

There'd never be another love, another time

She came into my life and made the living fine

She fills my heart

She fills my heart with very special things

With angels' songs, with wild imaginings

She fills my soul with so much love

That anywhere I go I'm never lonely

With her around, who could be lonely

I reach for her hand, it's always there

How long does it last

Can love be measured by the hours in a day

I have no answers now but this much I can say

I know I'll need her 'til the stars all burn away

And she'll be there

How long does it last

Can love be measured by the hours in a day

I have no answers now but this much I can say

I know I'll need her 'til the stars all burn away

And she'll be there


# Say You Say Me

Say you, say me

Say it for always

That's the way it should be

Say you, say me

Say it together, naturally

I had a dream, I had an awesome dream

People in the park playing games in the dark

And what they played was a masquerade

And from behind the walls of doubt

A voice was crying out

Say you, say me

Say it for always

That's the way it should be

Say you, say me

Say it together, naturally

As we go down life's lonesome highway

Seems the hardest thing to do is to find a friend or two

That helping hand

Someone who understands

That when you feel you've lost your way

You've got someone there to say, "I'll show you"

Say you, say me

Say it for always (oh)

That's the way it should be

Say you, say me

Say it together, naturally

So you think you know the answers? Oh no

Well the whole world's got you dancing

That's right, I'm telling you

Time to start believing, oh yes

Believe in who you are

You are a shining star

Say you, say me

Say it for always

Oh, that's the way it should be

Say you, say me

Say it together, naturally

Say it together, naturally

# All of Me
What would I do without your smart mouth?

Drawing me in, and you kicking me out

You've got my head spinning, no kidding, I can't pin you down

What's going on in that beautiful mind?

I'm on your magical mystery ride

And I'm so dizzy, don't know what hit me, but I'll be alright

My head's under water

But I'm breathing fine

You're crazy and I'm out of my mind

'Cause all of me

Loves all of you

Love your curves and all your edges

All your perfect imperfections

Give your all to me

I'll give my all to you

You're my end and my beginning

Even when I lose, I'm winning

'Cause I give you all of me

And you give me all of you, oh-oh

How many times do I have to tell you?

Even when you're crying, you're beautiful too

The world is beating you down, I'm around through every mood

You're my downfall, you're my muse

My worst distraction, my rhythm and blues

I can't stop singing, it's ringing in my head for you

My head's under water

But I'm breathing fine

You're crazy and I'm out of my mind

'Cause all of me

Loves all of you

Love your curves and all your edges

All your perfect imperfections

Give your all to me

I'll give my all to you

You're my end and my beginning

Even when I lose, I'm winning

'Cause I give you all of me

And you give me all of you, oh-oh

Give me all of you, oh

Cards on the table, we're both showing hearts

Risking it all, though it's hard

'Cause all of me

Loves all of you

Love your curves and all your edges

All your perfect imperfections

Give your all to me

I'll give my all to you

You're my end and my beginning

Even when I lose, I'm winning

'Cause I give you all of me

And you give me all of you

I give you all of me

And you give me all of you, oh-oh


# You Say


I keep fighting voices in my mind that say I'm not enough

Every single lie that tells me I will never measure up

Am I more than just the sum of every high and every low?

Remind me once again just who I am because I need to know

Ooh-oh

You say I am loved when I can't feel a thing

You say I am strong when I think I am weak

And you say I am held when I am falling short

And when I don't belong, oh, You say I am Yours

And I believe (I), oh, I believe (I)

What You say of me (I)

I believe

The only thing that matters now is everything You think of me

In You, I find my worth, in You, I find my identity

Ooh-oh

You say I am loved when I can't feel a thing

You say I am strong when I think I am weak

And you say I am held when I am falling short

When I don't belong, oh, You say I am Yours

And I believe (I), oh, I believe (I)

What You say of me (I)

Oh, I believe

Taking all I have, and now I'm laying it at Your feet

You have every failure, God, You have every victory

Ooh-oh

You say I am loved when I can't feel a thing

You say I am strong when I think I am weak

You say I am held when I am falling short

When I don't belong, oh, You say I am Yours

And I believe (I), oh, I believe (I)

What You say of me (I)

I believe

Oh, I believe (I)

Yes, I believe (I)

What You say of me (I)

I believe


# Flowers

We were good, we were gold

Kinda dream that can't be sold

We were right 'til we weren't

Built a home and watched it burn

Mm, I didn't wanna leave you, I didn't wanna lie

Started to cry, but then remembered I

I can buy myself flowers

Write my name in the sand

Talk to myself for hours

Say things you don't understand

I can take myself dancing

And I can hold my own hand

Yeah, I can love me better than you can

Can love me better, I can love me better, baby

Can love me better, I can love me better, baby

Paint my nails cherry red

Match the roses that you left

No remorse, no regret

I forgive every word you said

Ooh, I didn't wanna leave you, baby, I didn't wanna fight

Started to cry, but then remembered I

I can buy myself flowers

Write my name in the sand

Talk to myself for hours, yeah

Say things you don't understand

I can take myself dancing, yeah

I can hold my own hand

Yeah, I can love me better than you can

Can love me better, I can love me better, baby

Can love me better, I can love me better, baby

Can love me better, I can love me better, baby

Can love me better, I- (ooh, I)

I didn't wanna leave you, I didn't wanna fight

Started to cry, but then remembered I

I can buy myself flowers (uh-huh)

Write my name in the sand

Talk to myself for hours (yeah)

Say things you don't understand (you never will)

I can take myself dancing, yeah

I can hold my own hand

Yeah, I can love me better than

Yeah, I can love me better than you can

Can love me better, I can love me better, baby (oh, oh)

Can love me better, I can love me better, baby (than you can)

Can love me better, I can love me better, baby

Can love me better, I-

# How Deep Is Your Love


I know your eyes in the morning sun

I feel you touch me in the pouring rain

And the moment that you wander far from me

I wanna feel you in my arms again

And you come to me on a summer breeze

Keep me warm in your love, then you softly leave

And it's me you need to show

How deep is your love?

How deep is your love?

How deep is your love?

I really mean to learn

'Cause we're living in a world of fools

Breaking us down when they all should let us be

We belong to you and me

I believe in you

You know the door to my very soul

You're the light in my deepest, darkest hour

You're my savior when I fall

And you may not think I care for you

When you know down inside that I really do

And it's me you need to show

How deep is your love?

How deep is your love?

How deep is your love?

I really mean to learn

'Cause we're living in a world of fools

Breaking us down when they all should let us be

We belong to you and me

Na-na-na-na-na

Na-na-na-na-na-na-na-na

Na-na-na-na-na-na-na-na-na

Na-na-na-na-na-na-na

And you come to me on a summer breeze

Keep me warm in your love, then you softly leave

And it's me you need to show

How deep is your love?

How deep is your love?

How deep is your love?

I really mean to learn

'Cause we're living in a world of fools

Breaking us down when they all should let us be

We belong to you and me (na-na-na-na-na)

How deep is your love?

How deep is your love?

I really mean to learn

'Cause we're living in a world of fools

Breaking us down when they all should let us be

We belong to you and me (na-na-na-na-na)

How deep is your love?

How deep is your love?

I really mean to learn

'Cause we're living in a world of fools

Breaking us down when they all should let us be

We belong to you and me

# Words (Beegees)

Smile an everlasting smile

A smile can bring you near to me

Don't ever let me find you down

'Cause that would bring a tear to me

This world has lost its glory

Let's start a brand new story now, my love

Right now, there'll be no other time

And I can show you how, my love

Talk in everlasting words

And dedicate them all to me

And I will give you all my life

I'm here if you should call to me

You think that I don't even mean

A single word I say

It's only words and words are all I have

To take your heart away

You think that I don't even mean

A single word I say

It's only words and words are all I have

To take your heart away

It's only words and words are all I have

To take your heart away

It's only words and words are all I have

To take your heart away



# Words (F.R. David)

[Chorus]

Words don't come easy to me

How can I find a way to make you see I love you?

Words don't come easy

Words don't come easy to me

This is the only way for me to say I love you

Words don't come easy

[Verse 1]

Well, I'm just a music man, melodies are so far my best friend

But my words are coming out wrong, girl, I reveal my heart to you

And hope that you believe it's true 'cause


[Chorus]

Words don't come easy to me

How can I find a way to make you see I love you?

Words don't come easy


[Verse 2]

This is just a simple song that I've made for you on my own

There's no hidden meaning you know when I, when I say I love you, honey

Please believe, I really do 'cause

[Chorus]

Words don't come easy to me

How can I find a way to make you see I love you?

Words don't come easy

# Over and Over

I never dare to reach for the moon

I never thought I'd know heaven so soon

I couldn't hope to say how I feel

The joy in my heart no words can reveal

[REFRAIN]

Over and over I whisper your name

Over and over I kiss you again

I see the light of love in your eyes

Love is forever,no more good-byes

Now just a memory the tears that I cried

Now just a memory the sighs that I sighed

Dreams that I cherished all have come true

All my tomorrows I give to you


Life's summer leaves may turn into gold

The love that we share will never grow old

Here in your arms no words far away

Her in your arms forever I'll stay

Refrain twice

Lai...la...la...lai

# Hard To Say I'm Sorry

"Everybody needs a little time away"

I heard her say, from each other

Even lovers need a holiday

Far away, from each other


[Pre-Chorus: All]

Hold me now

It's hard for me to say I'm sorry

I just want you to stay

[Chorus: All]

After all that we've been through

I will make it up to you, I promise to

And after all that's been said and done

You're just the part of me I can't let go


Couldn't stand to be kept away
Just for the day, from your body

Wouldn't want to be swept away

Far away, from the one that I love


[Pre-Chorus: All]

Hold me now

It's hard for me to say I'm sorry

I just want you to know

Hold me now

I really want to tell you I'm sorry

I could never let you go

# You Are Only Lonely

When the world is ready to fall on your little shoulders

And, when you're feeling lonely and small,

You need somebody there to hold you;

You can call out my name

When you're only lonely;

Now, don't you ever be ashamed;

You're only lonely.

When you need somebody around on the nights that try you

I was there when you were a queen

And I'll be the last one there beside you;

So you can call out my name

When you're only lonely;

Now, don't you ever be ashamed;

You're only lonely. (You're only lonely)

(You're only lonely) (You're only lonely)

Ooh, When the world is ready to fall on your little shoulders

And, when you're feeling lonely and small,

You need somebody there to hold you;

So don't you ever be ashamed

When you're only lonely;

You can call out my name

When you're only lonely; (You're only lonely)

When you're only lonely; (You're only lonely)

Ooh, it's no crime,

Darlin', we got lots of time,

Woh, woh, (You're only lonely)

Woh, woh, woh, (You're only lonely)

No there's nothing wrong with you,

Darlin, I get lonely too.

(You're only lonely)(You're only lonely)

So, if you need me, (You're only lonely)

All you've gotta do is call me

Well, you're only lonely

(You're only lonely)(You're only lonely)

Ooh, ooh, (You're only lonely)

# Time In A Bottle


If I could save time in a bottle

The first thing that I'd like to do

Is to save every day

'Til eternity passes away

Just to spend them with you

If I could make days last forever

If words could make wishes come true

I'd save every day like a treasure and then

Again, I would spend them with you

But there never seems to be enough time

To do the things you want to do

Once you find them

I've looked around enough to know

That you're the one I want to go

Through time with

If I had a box just for wishes

And dreams that had never come true

The box would be empty

Except for the memory

Of how they were answered by you

But there never seems to be enough time

To do the things you want to do

Once you find them

I've looked around enough to know

That you're the one I want to go

Through time with

# Perfect

I found a love for me

Oh, darling, just dive right in and follow my lead

Well, I found a girl, beautiful and sweet

Oh, I never knew you were the someone waitin' for me

'Cause we were just kids when we fell in love, not knowin' what it was

I will not give you up this time

Oh, darling, just kiss me slow, your heart is all I own

And in your eyes, you're holding mine

Baby, I'm dancin' in the dark with you between my arms

Barefoot on the grass while listenin' to our favourite song

When you said you looked a mess, I whispered underneath my breath

But you heard it, "Darling, you look perfect tonight"

Well, I found a woman, stronger than anyone I know

She shares my dreams, I hope that someday, I'll share her home

I found a love to carry more than just my secrets

To carry love, to carry children of our own

We are still kids, but we're so in love, fightin' against all odds

I know we'll be alright this time

Darling, just hold my hand, be my girl, I'll be your man

I see my future in your eyes

Oh, baby, I'm dancin' in the dark with you between my arms

Barefoot on the grass while listenin' to our favourite song

When I saw you in that dress, lookin' so beautiful

I don't deserve this, darling, you look perfect tonight

No, no, no

Mm, oh

Baby, I'm dancin' in the dark with you between my arms

Barefoot on the grass, oh, listenin' to our favourite song

I have faith in what I see, now I know I have met

An angel in person, and she looks perfect

Though I don't deserve this, you look perfect tonight