# Top of the world

Such a feelin's comin' over me

There is wonder in most every thing I see

Not a cloud in the sky, got the sun in my eyes

And I won't be surprised if it's a dream

Everything I want the world to be

Is now comin' true especially for me

And the reason is clear, it's because you are here

You're the nearest thing to heaven that I've seen

I'm on the top of the world lookin' down on creation

And the only explanation I can find

Is the love that I've found, ever since you've been around

Your love's put me at the top of the world

Something in the wind has learned my name

And it's tellin' me that things are not the same

In the leaves on the trees, and the touch of the breeze

There's a pleasing sense of happiness for me

There is only one wish on my mind

When this day is through I hope that I will find

That tomorrow will be, just the same for you and me

All I need will be mine if you are here

I'm on the top of the world lookin' down on creation

And the only explanation I can find

Is the love that I've found, ever since you've been around

Your love's put me at the top of the world

I'm on the top of the world lookin' down on creation

And the only explanation I can find

Is the love that I've found, ever since you've been around

Your love's put me at the top of the world

# Love me like You do

You're the light, you're the night

You're the colour of my blood

You're the cure, you're the pain

You're the only thing I wanna touch

Never knew that it could mean so much, so much

You're the fear, I don't care

'Cause I've never been so high

Follow me through the dark

Let me take you past the satellites

You can see the world you brought to life, to life

So love me like you do, lo-lo-love me like you do

Love me like you do, lo-lo-love me like you do

Touch me like you do, to-to-touch me like you do

What are you waiting for?

Fading in, fading out

On the edge of paradise

Every inch of your skin

Is a holy grail I've gotta find

Only you can set my heart on fire, on fire, yeah

I'll let you set the pace

'Cause I'm not thinkin' straight

My head's spinnin' around, I can't see clear no more

What are you waiting for?

So love me like you do, lo-lo-love me like you do

Love me like you do, lo-lo-love me like you do

Touch me like you do, to-to-touch me like you do

Oh, what are you waiting for?

So love me like you do, lo-lo-love me like you do

Love me like you do, lo-lo-love me like you do

Touch me like you do, to-to-touch me like you do

What are you waiting for?

I'll let you set the pace

'Cause I'm not thinkin' straight

My head's spinnin' around, I can't see clear no more

Oh, what are you waiting for?

Lo-lo-love me like you do

Love me like you do, lo-lo-love me like you do, oh

Touch me like you do, to-to-touch me like you do, oh-oh

Aw, what are you waiting for?

So love me like you do, lo-lo-love me like you do

Love me like you do, lo-lo-love me like you do, oh

Touch me like you do, to-to-touch me like you do, oh-oh

Oh, what are you waiting for?

Ah

Ah, ah


# Can you feel the love tonight

There's a calm surrender to the rush of day

When the heat of the rolling world can be turned away

An enchanted moment, and it sees me through

It's enough for this restless warrior just to be with you

And can you feel the love tonight?

It is where we are

It's enough for this wide-eyed wanderer

That we got this far

And can you feel the love tonight?

How it's laid to rest

It's enough to make kings and vagabonds

Believe the very best

There's a time for everyone if they only learn

That the twisting kaleidoscope moves us all in turn

There's a rhyme and reason to the wild outdoors

When the heart of this star-crossed voyager beats in time with yours

And can you feel the love tonight?

It is where we are

It's enough for this wide-eyed wanderer

That we got this far

And can you feel the love tonight?

How it's laid to rest

It's enough to make kings and vagabonds

Believe the very best

It's enough to make kings and vagabonds

Believe the very best

# Careless Whisper

Oh, whoa, whoa, oh
I feel so unsure

As I take your hand and lead you to the dance floor

As the music dies, something in your eyes

Calls to mind a silver screen and all its sad goodbyes

I'm never gonna dance again

Guilty feet have got no rhythm

Though it's easy to pretend

I know you're not a fool

I should have known better than to cheat a friend

And waste the chance that I'd been given

So I'm never gonna dance again

The way I danced with you, oh

Time can never mend

The careless whispers of a good friend

To the heart and mind, ignorance is kind

There's no comfort in the truth, pain is all you'll find

I'm never gonna dance again

Guilty feet have got no rhythm

Though it's easy to pretend

I know you're not a fool

I should have known better than to cheat a friend (shoulda known better, yeah)

And waste the chance that I'd been given

So I'm never gonna dance again

The way I danced with you, oh

Never without your love

Tonight, the music seems so loud

I wish that we could lose this crowd

Maybe it's better this way

We'd hurt each other with the things we want to say

We could have been so good together

We could have lived this dance forever

But now, who's gonna dance with me?

Please, stay

And I'm never gonna dance again

Guilty feet have got no rhythm

Though it's easy to pretend

I know you're not a fool

I should have known better than to cheat a friend

And waste the chance that I'd been given

So I'm never gonna dance again

The way I danced with you, oh

Now that you're gone

(Now that you're gone)


Was what I did so wrong, so wrong

That you had to leave me alone


# You needed me

I cried a tear, you wiped it dry

I was confused, you cleared my mind

I sold my soul, you bought it back for me

And held me up and gave me dignity

Somehow you needed me



You gave me strength to stand alone again

To face the world out on my own again

You put me high upon a pedestal

So high that I could almost see eternity

You needed me, you needed me



And I can't believe it's you

I can't believe it's true

I needed you and you were there

And I'll never leave, why should I leave?

I'd be a fool 'cause I finally found someone who really cares



You held my hand when it was cold

When I was lost you took me home

You gave me hope when I was at the end

And turned my lies back into truth again

You even called me "friend"



You gave me strength to stand alone again

To face the world out on my own again

You put me high upon a pedestal

So high that I could almost see eternity

You needed me, you needed me



You needed me, you needed me





# Die For You


I'm findin' ways to articulate the feelin' I'm goin' through

I just can't say I don't love you (Yeah)

'Cause I love you, yeah

It's hard for me to communicate the thoughts that I hold

But tonight, I'm gon' let you know

Let me tell the truth

Baby, let me tell the truth, yeah



You know what I'm thinkin', see it in your eyes

You hate that you want me, hate it when you cry

You're scared to be lonely, 'specially in the night

I'm scared that I'll miss you, happens every time

I don't want this feelin', I can't afford love

I try to find a reason to pull us apart

It ain't workin' 'cause you're perfect

And I know that you're worth it

I can't walk away, oh



Even though we're goin' through it

And it makes you feel alone

Just know that I would die for you

Baby, I would die for you, yeah

The distance and the time between us

It'll never change my mind 'cause

Baby, I would die for you

Baby, I would die for you, yeah (Say)



I'm findin' ways to manipulate the feelin' you're goin' through

But, baby girl, I'm not blamin' you

Just don't blame me, too, yeah

'Cause I can't take this pain forever

And you won't find no one that's better

'Cause I'm right for you, babe

I think I'm right for you, babe



You know what I'm thinkin', see it in your eyes

You hate that you want me, hate it when you cry

It ain't workin' 'cause you're perfect

And I know that you're worth it

I can't walk away, oh



Even though we're goin' through it

And it makes you feel alone

Just know that I would die for you

Baby, I would die for you, yeah

The distance and the time between us

It'll never change my mind 'cause

Baby, I would die for you, uh

Baby, I would die for you, yeah



I would die for you, I would lie for you

Keep it real with you, I would kill for you, my baby

I'm just sayin', yeah

I would die for you, I would lie for you

Keep it real with you, I would kill for you, my baby

Na-na-na, na-na-na, na-na-na



Even though we're goin' through it

And it makes you feel alone

Just know that I would die for you

Baby, I would die for you, yeah

The distance and the time between us

It'll never change my mind 'cause

Baby, I would die for you

Baby, I would die for you, yeah (Oh, babe)



(Die for you)



# It must have been Love

Lay a whisper on my pillow

Leave the winter on the ground

I wake up lonely, there's air of silence

In the bedroom and all around


Touch me now, I close my eyes

And dream away


It must have been love but it's over now

It must have been good but I lost it somehow

It must have been love but it's over now

From the moment we touched till the time had run out



Make believing we're together

That I'm sheltered by your heart

But in and outside, I turned to water

Like a teardrop in your palm



And it's a hard winter's day

I dream away


It must have been love but it's over now

It was all that I wanted, now, I'm living without

It must have been love but it's over now

It's where the water flows, it's where the wind blows



It must have been love but it's over now

It must have been good but I lost it somehow

It must have been love but it's over now

From the moment we touched till the time had run out



Yeah, it must have been love but it's over now

It was all that I wanted, now, I'm living without

It must have been love but it's over now

It's where the water flows, it's where the wind blows



It must have been love but it's over now

It must have been love but it's over now


# Thinking Outloud

When your legs don't work like they used to before

And I can't sweep you off of your feet

Will your mouth still remember the taste of my love

Will your eyes still smile from your cheeks

And darling I will be loving you 'til we're 70

And baby my heart could still fall as hard at 23

And I'm thinking 'bout how people fall in love in mysterious ways

Maybe just the touch of a hand

Oh me I fall in love with you every single day

And I just wanna tell you I am

So honey now

Take me into your loving arms

Kiss me under the light of a thousand stars

Place your head on my beating heart

I'm thinking out loud

Maybe we found love right where we are

When my hair's all but gone and my memory fades

And the crowds don't remember my name

When my hands don't play the strings the same way, mm

I know you will still love me the same

'Cause honey your soul can never grow old, it's evergreen

Baby your smile's forever in my mind and memory

I'm thinking 'bout how people fall in love in mysterious ways

Maybe it's all part of a plan

I'll just keep on making the same mistakes

Hoping that you'll understand

But baby now

Take me into your loving arms

Kiss me under the light of a thousand stars

Place your head on my beating heart

I'm thinking out loud

That maybe we found love right where we are, oh

So baby now

Take me into your loving arms

Kiss me under the light of a thousand stars

Oh darling, place your head on my beating heart

I'm thinking out loud

That maybe we found love right where we are

Oh baby, we found love right where we are (maybe)

And we found love right where we are

# Midnight Blue

Midnight blue so lonely without you

Dreams fed by the memories

Oh let the music play

Midnight blue those treasured thoughts of you

Gone now and forever

Please

Let the music play

Midnight

Midnight

I forgave you

Couldn't save you

Drove you from my mind

Midnight blue - so lonely without you

Warm words from a fantasy

Oh let the music play

Midnight blue - the tears come flowing through

I'll never forget you

Please

Let the music play

Midnight

Midnight

Midnight blue those treasured thoughts of you

Gone now and forever please

Let the music play
